version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Zipping app..."
      - zip -r app.zip . || true

artifacts:
  files:
    - app.zip
  discard-paths: yes
